<h1> THIS IS HELL AND I'm NOT LIKING IT AS IT HAS BEEN A BIG TASK AND UNABLE TO PERFORM IT ON TIME AND IS TAKING A VERY LONG TIME TO EXECUTE </h1>
<h2> THIS IS SAMPLE PROGRAM FOR PRACTICE !!! </h2>
<h3> CONTINUOUS INTEGRATION USING POLL SCM A NEW FEATURE </h3>
<h2> January 3rd 2020 </h2>
